services:
  web:
    image: httpd
    container_name: webserver
    ports:
      - 8001:80
      - 4431:443
    volumes:
      - ./static/:/usr/local/apache2/htdocs/
    networks:
      - net0

networks:
  net0:
